[project]
name = "dependency-mapping"
version = "0.1.0"
description = "A tool to visualize dependencies between Python packages"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyqt5",
    "matplotlib",
    "networkx",
    "scipy"
]
